total_environments: 8
hidden_size: 32
action_size: 4
horizon: 32
max_steps: 108000
frame_stack: 4
learning_rate: 2.5e-4
clip_param: 0.2
value_loss_coef: 0.5
entropy_coef: 0.01
num_epochs: 2
mini_batch_size: 64
num_mini_batches: 4
gae_discount: 0.99
gae_lambda: 0.95
max_gradient_norm: 0.5
num_rollouts: 10
log_episode_frequency: 1
num_workers: 1
worker_batch_size: 1
frame_skip: 4
# Breakout max possible score.
max_return: 864
record_observation: false
