total_environments: 8
hidden_size: 512
action_size: 4
horizon: 128
max_steps: 64800
frame_stack: 4
learning_rate: 0.00025
clip_param: 0.1
value_loss_coef: 0.5
entropy_coef: 0.01
num_epochs: 4
mini_batch_size: 256
num_mini_batches: 4
gae_discount: 0.99
gae_lambda: 0.95
max_gradient_norm: 0.5
num_rollouts: 9760
num_workers: 8
worker_batch_size: 1
frame_skip: 4
# Breakout max possible score.
max_return: 864
record_observation: false
record_video: true
cuda_graph: false
deterministic: true