  total_environments: 1024
  hidden_size: 512
  action_size: 4
  horizon: 128
  max_steps: 108000
  frame_stack: 4
  learning_rate: 2.5e-4
  clip_param: 0.2
  value_loss_coef: 0.5
  entropy_coef: 0.01
  num_epochs: 1
  mini_batch_size: 2048
  num_mini_batches: 64
  gae_discount: 0.99
  gae_lambda: 0.95
  max_gradient_norm: 0.5
  num_rollouts: 7000
  log_episode_frequency: 10
  num_workers: 32
  worker_batch_size: 32
  frame_skip: 4
